import {
  GAUNTLET_LEVEL_ID,
  type GauntletLevelId,
} from "./gauntlet-level-ids.ts";

export const CHINA_CAMPAIGN_RULESET_VERSION = 1;

export const CHINA_CAMPAIGN_REQUIRED_LEVEL_IDS: readonly GauntletLevelId[] = [
  GAUNTLET_LEVEL_ID.PROVINCE_SHAPE,
  GAUNTLET_LEVEL_ID.CITY_PROVINCE,
  GAUNTLET_LEVEL_ID.PLATE_PLACE,
  GAUNTLET_LEVEL_ID.PROVINCE_NEIGHBORS,
  GAUNTLET_LEVEL_ID.PLATE_COMPLETION,
  GAUNTLET_LEVEL_ID.CITY_MAP,
  GAUNTLET_LEVEL_ID.TRUTH_FLASH,
  GAUNTLET_LEVEL_ID.NEIGHBOR_CHAIN,
  GAUNTLET_LEVEL_ID.CITY_UNDERCOVER,
  GAUNTLET_LEVEL_ID.REGION_MAP,
  GAUNTLET_LEVEL_ID.TERRITORY_GROUPS,
  GAUNTLET_LEVEL_ID.GEOGRAPHY_ELIMINATION,
  GAUNTLET_LEVEL_ID.PLATE_FAULT,
  GAUNTLET_LEVEL_ID.UNIVERSITY_CITY,
  GAUNTLET_LEVEL_ID.CONFUSABLE_CITIES,
  GAUNTLET_LEVEL_ID.PROVINCE_CITY_COUNT,
  GAUNTLET_LEVEL_ID.CITY_NEIGHBORS,
  GAUNTLET_LEVEL_ID.PLATE_CITY_MAP,
  GAUNTLET_LEVEL_ID.FINAL_BOSS,
] as const;

export function hasCompletedChinaCampaign(levelIds: Iterable<string>) {
  const completed = new Set(levelIds);
  return CHINA_CAMPAIGN_REQUIRED_LEVEL_IDS.every((levelId) =>
    completed.has(levelId)
  );
}
